### ISSUE TITLE
Notifications appearing in a closed group for your own message

### ISSUE THREAD

**Issue by CertifiedRascal** [oxen-io/session-ios#343]
**Bug Description**
In a closed group, after sending a message, a few seconds later a notification will pop up for a new session message. However, going to the messages reveals no new messages. I assume it is actually notifying from the message you sent in the group which doesn't make much sense. In general, messages do take a bit to appear which is expected from having to go through the nodes, but in this case, after waiting a bit there is nothing new that shows.

**To reproduce**

Create a closed group with a few people and send a message. Then, close the app (just go to the home screen) and lock the phone. A few moments later, a notification should show for a new session message. Upon re-entering the app, no new messages will be seen.

**Smartphone (please complete the following information):**

 - Device: iPhoneXr
 - OS: iOS 14.3
 - Version of Session or latest commit hash: 1.7.5

**Comment by LokiNugget** [comment]
I came here to log the same issue.

Reproducible for me in the same use case.

**Comment by nielsandriesse** [comment]
This should now be fixed.

**Comment by Marky-N** [comment]
@nielsandriesse This still happens on iOS 14.4 with Session 1.9.1 (206)
